version: "2.0"
services:
  mysql:
    image: mysql:5.7
    container_name: ixionlegrandmonarque
    environment:
      MYSQL_ROOT_PASSWORD: ixionlegrandmonarque
      MYSQL_USER: ixionlegrandmonarque
      MYSQL_PASSWORD: ixionlegrandmonarque
      MYSQL_DATABASE: ixionlegrandmonarque
    ports:
      - '3270:3306'