services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Controller\TeamMiamController:
        autowire: true;

    App\LeagueOfLegends\TeamMiamManager:
        autowire: true;

    App\LoLDataGetter\ApiType\SummonerV4:
        autowire: true;
